name: Deploy App

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Copy app
        run: |
          scp -o StrictHostKeyChecking=no -r app ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/
      - name: Install requirements and restart
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} <<'EOF2'
          sudo pip3 install -r /home/ubuntu/app/requirements.txt
          sudo pkill -f app.py || true
          nohup python3 /home/ubuntu/app/app.py &
          EOF2
